Switched from something that works only for gcc to something that works for gcc and clang. Original error is:
robothw_interfaces.h:60:68: error: typedef 'value_type' cannot be referenced with a class specifier.